# Generated by Django 5.2.10 on 2026-02-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('locked', 'Locked'), ('pending', 'Pending')], default='active', max_length=20),
        ),
    ]
