# Generated by Django 5.2.10 on 2026-02-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_alter_agency_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
